export const trainingPlan = {
  weekly_schedule: [
    {
      day: 'Понедельник',
      activities: [
        {
          id: 1,
          name: 'Разминка',
          time: '10:00-10:10',
          status: 'active',
          description:
            'Легкая кардио-разминка на беговой дорожке или эллипсоиде.',
          type: 'cardio',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'treadmill',
        },
        {
          id: 2,
          name: 'Приседания со штангой',
          time: '10:10-10:20',
          status: 'active',
          description: 'Силовое упражнение для ног и ягодиц.',
          type: 'strength',
          intensity: 'high',
          duration: '10 minutes',
          equipment: 'barbell',
        },
        {
          id: 3,
          name: 'Тяга мертвого груза',
          time: '10:20-10:30',
          status: 'active',
          description:
            'Основное упражнение для развития нижней части тела и спины.',
          type: 'strength',
          intensity: 'high',
          duration: '10 minutes',
          equipment: 'barbell',
        },
        {
          id: 4,
          name: 'Выпады с гантелями',
          time: '10:30-10:40',
          status: 'active',
          description:
            'Упражнение для укрепления мышц ног и улучшения баланса.',
          type: 'strength',
          intensity: 'medium',
          duration: '10 minutes',
          equipment: 'dumbbells',
        },
        {
          id: 5,
          name: 'Жим ногами в тренажере',
          time: '10:40-10:50',
          status: 'active',
          description:
            'Упражнение на мышцы ног в специализированном тренажере.',
          type: 'strength',
          intensity: 'high',
          duration: '10 minutes',
          equipment: 'leg press machine',
        },
        {
          id: 6,
          name: 'Растяжка и восстановление',
          time: '10:50-11:00',
          status: 'active',
          description:
            'Заминка с растяжкой для улучшения гибкости и предотвращения мышечного напряжения.',
          type: 'stretching',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'mat',
        },
      ],
    },
    {
      day: 'Вторник',
      activities: [
        {
          id: 7,
          name: 'Разминка',
          time: '10:00-10:10',
          status: 'active',
          description:
            'Бег на месте и скакалка для подготовки тела к активной тренировке.',
          type: 'warm-up',
          intensity: 'medium',
          duration: '10 minutes',
          equipment: 'jump rope',
        },
        {
          id: 8,
          name: 'Кардио HIIT',
          time: '10:10-10:25',
          status: 'active',
          description:
            'Высокоинтенсивная интервальная тренировка для улучшения выносливости и сжигания калорий.',
          type: 'cardio',
          intensity: 'high',
          duration: '15 minutes',
          equipment: 'none',
        },
        {
          id: 9,
          name: 'Планка',
          time: '10:25-10:30',
          status: 'active',
          description: 'Статическое упражнение для укрепления мышц кора.',
          type: 'core',
          intensity: 'medium',
          duration: '5 minutes',
          equipment: 'mat',
        },
        {
          id: 10,
          name: 'Скручивания на пресс',
          time: '10:30-10:40',
          status: 'active',
          description: 'Упражнение на пресс для формирования мышц живота.',
          type: 'core',
          intensity: 'medium',
          duration: '10 minutes',
          equipment: 'mat',
        },
        {
          id: 11,
          name: 'Подъемы ног в висе на турнике',
          time: '10:40-10:50',
          status: 'active',
          description:
            'Эффективное упражнение для нижнего пресса и укрепления мышц живота.',
          type: 'core',
          intensity: 'high',
          duration: '10 minutes',
          equipment: 'pull-up bar',
        },
        {
          id: 12,
          name: 'Заминка и растяжка',
          time: '10:50-11:00',
          status: 'active',
          description:
            'Легкая заминка и растяжка для улучшения гибкости и восстановления.',
          type: 'stretching',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'mat',
        },
      ],
    },
    {
      day: 'Среда',
      activities: [
        {
          id: 13,
          name: 'Разминка',
          time: '10:00-10:10',
          status: 'active',
          description: 'Легкая кардио-разминка для активизации тела.',
          type: 'cardio',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'none',
        },
        {
          id: 14,
          name: 'Жим штанги лежа',
          time: '10:10-10:25',
          status: 'active',
          description: 'Базовое упражнение для грудных мышц.',
          type: 'strength',
          intensity: 'high',
          duration: '15 minutes',
          equipment: 'bench, barbell',
        },
        {
          id: 15,
          name: 'Тяга штанги в наклоне',
          time: '10:25-10:40',
          status: 'active',
          description: 'Упражнение для укрепления мышц спины.',
          type: 'strength',
          intensity: 'high',
          duration: '15 minutes',
          equipment: 'barbell',
        },
        {
          id: 16,
          name: 'Разведение гантелей стоя',
          time: '10:40-10:50',
          status: 'active',
          description: 'Упражнение для задней дельтовидной мышцы.',
          type: 'strength',
          intensity: 'medium',
          duration: '10 minutes',
          equipment: 'dumbbells',
        },
        {
          id: 17,
          name: 'Подъем штанги на бицепс',
          time: '10:50-11:00',
          status: 'active',
          description: 'Классическое упражнение для бицепса.',
          type: 'strength',
          intensity: 'medium',
          duration: '10 minutes',
          equipment: 'barbell',
        },
        {
          id: 18,
          name: 'Растяжка',
          time: '11:00-11:10',
          status: 'active',
          description: 'Растяжка для восстановления после тренировки.',
          type: 'stretching',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'mat',
        },
      ],
    },
    {
      day: 'Четверг',
      activities: [
        {
          id: 19,
          name: 'Разминка',
          time: '10:00-10:10',
          status: 'active',
          description: 'Активизация тела с помощью легкой кардио.',
          type: 'cardio',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'none',
        },
        {
          id: 20,
          name: 'Скакалка',
          time: '10:10-10:20',
          status: 'active',
          description: 'Высокоинтенсивное кардио упражнение.',
          type: 'cardio',
          intensity: 'high',
          duration: '10 minutes',
          equipment: 'jump rope',
        },
        {
          id: 21,
          name: 'Приседания',
          time: '10:20-10:35',
          status: 'active',
          description: 'Приседания со штангой для развития нижней части тела.',
          type: 'strength',
          intensity: 'high',
          duration: '15 minutes',
          equipment: 'barbell',
        },
        {
          id: 22,
          name: 'Жим ногами',
          time: '10:35-10:45',
          status: 'active',
          description: 'Упражнение для квадрицепсов и ягодиц.',
          type: 'strength',
          intensity: 'high',
          duration: '10 minutes',
          equipment: 'leg press machine',
        },
        {
          id: 23,
          name: 'Отжимания',
          time: '10:45-10:55',
          status: 'active',
          description: 'Классическое упражнение для груди, плеч и трицепсов.',
          type: 'strength',
          intensity: 'medium',
          duration: '10 minutes',
          equipment: 'none',
        },
        {
          id: 24,
          name: 'Заминка и растяжка',
          time: '10:55-11:05',
          status: 'active',
          description: 'Легкая заминка и растяжка после тренировки.',
          type: 'stretching',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'mat',
        },
      ],
    },
    {
      day: 'Пятница',
      activities: [
        {
          id: 25,
          name: 'Разминка',
          time: '10:00-10:10',
          status: 'active',
          description: 'Легкая кардио-разминка для подготовки тела к нагрузке.',
          type: 'cardio',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'none',
        },
        {
          id: 26,
          name: 'Кроссфит',
          time: '10:10-10:40',
          status: 'active',
          description: 'Комбинация упражнений на силу и выносливость.',
          type: 'crossfit',
          intensity: 'high',
          duration: '30 minutes',
          equipment: 'various',
        },
        {
          id: 27,
          name: 'Тяга гантели одной рукой',
          time: '10:40-10:50',
          status: 'active',
          description: 'Упражнение для спины и бицепса.',
          type: 'strength',
          intensity: 'medium',
          duration: '10 minutes',
          equipment: 'dumbbell',
        },
        {
          id: 28,
          name: 'Плиометрические прыжки',
          time: '10:50-11:00',
          status: 'active',
          description: 'Упражнения на развитие взрывной силы и скорости.',
          type: 'plyometrics',
          intensity: 'high',
          duration: '10 minutes',
          equipment: 'none',
        },
        {
          id: 29,
          name: 'Бег трусцой',
          time: '11:00-11:10',
          status: 'active',
          description: 'Легкая кардио-разминка для восстановления.',
          type: 'cardio',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'none',
        },
        {
          id: 30,
          name: 'Растяжка',
          time: '11:10-11:20',
          status: 'active',
          description:
            'Глубокая растяжка для предотвращения травм и улучшения гибкости.',
          type: 'stretching',
          intensity: 'low',
          duration: '10 minutes',
          equipment: 'mat',
        },
      ],
    },
  ],
};
